blog/urls.py
#coding:utf-8

from django.conf.urls import url
import views

# app_name是为了reverse函数准备的
app_name = "blog"
# ^$代表了空字符串
urlpatterns = [
    url(r'^blog/$', views.IndexView.as_view(), name="index"),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^blog/archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name="archives"),
    url(r'^blog/category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^blog/tag/(?P<pk>[0-9]+)/$', views.TagViews.as_view(), name="tag"),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('webuser.urls')),
    url(r'', include('movie.urls')),
    url(r'', include('questions.urls')),
    url(r'', include('webchat.urls')),
    url(r'', include('weixin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
#coding:utf-8

from django.conf.urls import url
import views

# app_name是为了reverse函数准备的
app_name = "movie"
# ^$代表了空字符串
urlpatterns = [
    url(r'^getmovielist/$', views.get_movie_list, name="getmovielist"),
    url(r'^getlatestmovielist/$', views.get_latest_movielist, name="getlatestmovielist"),
    url(r'^getfilmfestlist/$', views.get_filmfest_list, name="getfilmfestlist"),
    url(r'^searchmovie/$', views.search_movie, name="searchmovie"),
    url(r'^movie/(?P<movie_id>[0-9]+)/$', views.movie, name="movie"),
    url(r'^ranking_list/playmostmovies/$', views.get_playmostmovies, name="playmostmovies"),
    url(r'^ranking_list/box_officemovies/$', views.get_box_officemovies, name="box_officemovies"),
    url(r'^ranking_list/good_evaluationmovies/$', views.get_good_evaluationmovies, name="good_evaluationmovies"),
]

movie/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import markdown

from django.db import models
from django.contrib.auth.models import User

from datetime import datetime

class MovieRankings(models.Model):
    """
    各种电影排行榜.
    """
    name = models.CharField(max_length=100)
    def __unicode__(self):
        return self.name

class Movie(models.Model):
    """
    电影的数据库表格
    """
    movie_name = models.CharField(max_length=64, blank=True)
    # 豆瓣链接,值可以是null,也可以不填这个字段.
    douban_link = models.CharField(max_length=256, null=True, blank=True)
    # 豆瓣评分.
    douban_score = models.CharField(max_length=64, null=True, blank=True)
    # 豆瓣评分人数.
    douban_counter = models.PositiveIntegerField(default=0, blank=True)
    # Imdb链接.
    imdb_link = models.CharField(max_length=256, null=True, blank=True)
    # Imdb评分.
    imdb_score = models.CharField(max_length=64, null=True, blank=True)
    # Imdb评分人数.
    imdb_counter = models.PositiveIntegerField(default=0, blank=True)
    # 网站中的链接.
    nomovie_link = models.CharField(max_length=256, null=True, blank=True)
    # 网站中评分.
    nomovie_score = models.CharField(max_length=64, null=True, blank=True)
    # 网站中评分人数.
    nomovie_counter = models.PositiveIntegerField(default=0, blank=True)
    # 上映国家.
    country = models.CharField(max_length=64, null=True, blank=True)
    # 上映日期.
    dateyear = models.CharField(max_length=64, null=True, blank=True)
    # 主演.
    actor = models.CharField(max_length=256, null=True, blank=True)
    # 导演.
    director = models.CharField(max_length=256, null=True, blank=True)
    # 电影类型.
    style = models.CharField(max_length=64, null=True, blank=True)
    # 电影播放地址.
    movie_address = models.CharField(max_length=256, null=True, blank=True)
    # 电影下载链接.
    download_link = models.CharField(max_length=256, null=True, blank=True)
    # 电影在本网站的播放次数.
    counter = models.PositiveIntegerField(default=0, blank=True)
    # 电影来源,
    # 0:表示豆瓣top250 1:表示imdbtop250 2:表示普通豆瓣 3：表示普通imdb  
    # 4:表示在豆瓣和imdb中都存在 5表示：用户自添加
    original = models.CharField(max_length=256, null=True, blank=True)
    # 1:表示通过 0:表示未通过 2:表示审核中
    status = models.IntegerField(null=True, blank=True)
    # 图片保存地址
    image = models.CharField(max_length=256, null=True, blank=True)
    # 爬取电影入库时间
    spidertime = models.DateTimeField(auto_now_add=True, null=True)
    # 关于电影
    aboutmovie = models.CharField(max_length=256, null=True, blank=True)
    # 电影语言
    language = models.CharField(max_length=64, null=True, blank=True)
    # 电影天堂搜索地址
    dyttsearch = models.CharField(max_length=256, null=True, blank=True)
    # 电影天堂搜索电影详情页面
    dyttdetail = models.CharField(max_length=256, null=True, blank=True)
    movierankings = models.ForeignKey(MovieRankings, null=True, blank=True)

    def __unicode__(self):
        return self.movie_name

    # def get_comments(self):

class MovieHistory(models.Model):
    # 观看的用户.
    # 用户一对多MovieHistory,可以看多个电影.
    user = models.ForeignKey(User)
    # 观看的电影.
    movie = models.ForeignKey(Movie)
    # 观看的时间.
    date = models.DateTimeField(auto_now_add=True)
    # 0表示用户观看了该电影,1表示收藏,2表示推荐.
    marked = models.IntegerField(blank=True, null=True)
    
    def __unicode__(self):
        return "{%s}--{%s}" % (self.user.username, self.movie.movie_name)

movie/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import random

from django.db.models.query import QuerySet
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views.generic import ListView

from webuser.models import Webuser
from blog.utils import pagination_data
from models import Movie, MovieHistory
from templatetags.movie_tags import get_play_most_movies, get_good_evaluation_movies, get_box_office_movies

movie_area = ["阿根廷","巴西","澳大利亚","西班牙","南非","爱尔兰","伊朗","不丹","奥地利",
              "卢森堡","比利时","丹麦"]

def get_movie_list(request):
    """
    获得推荐电影列表和默认电影列表
    """
    LIKE_STYLE_CHOICE = {0:"动作", 1:"悬疑", 2:"爱情", 3:"科幻", 4:"恐怖", 5:"犯罪", 6:"其他"}
    OTHER_LIKE_STYLE = ["剧情", "喜剧", "动画", "纪录片", "情色", "战争", "历史", "惊悚"]

    # 为了区别网页上用户选择的选项块.
    action = "getmovielist"
    choice_type = "suggest"
    # 获取用户请求页的页码,例如:?page=12.
    page = request.GET.get("page")
    if page is not None:
        page = int(page)
    else:
        page = 1
    filtertype = request.GET.get("filtertype")
    filterparam = request.GET.get("filterparam")
    # 过滤条件为有播放地址,豆瓣分数大于7.5,豆瓣评分人数大于2000人的电影.
    # __gte大于的含义
    # moviequery = Movie.objects.filter(movie_address__isnull=False, 
    #                                   douban_score__gte=7.5,
    #                                   douban_counter__gte=2000)
    user = request.user
    # 通过验证
    if user.is_authenticated(): 
        # 如果用户没有设置自己喜爱的电影偏好,就给出全部电影.
        if user.webuser.likesstyle == None:
            movie_list = Movie.objects.all().order_by("-douban_score", "-douban_counter")
        else:
            # 给用户推荐的电影列表.
            likestyle_list = []
            # 空的集合
            movie_list = Movie.objects.none()
            for likestyle in user.webuser.likesstyle[1:-1].split(","):
                likestyle_list.append(LIKE_STYLE_CHOICE[int(likestyle.strip()[2])])
            for likestyle in likestyle_list:
                if likestyle == "其他":
                    for other in OTHER_LIKE_STYLE:
                        movie_list_other = Movie.objects.filter(style__contains=other)
                        # 合并集合
                        movie_list = movie_list | movie_list_other                       
                movie_list_style = Movie.objects.filter(style__contains=likestyle)
                # 合并集合
                movie_list = movie_list | movie_list_style
            movie_list = movie_list.order_by("-douban_score", "-douban_counter")

        # 如果用户选择了style,在电影队列中进行过滤style的字段
        if filtertype == "style":
            movie_list = Movie.objects.filter(style__contains=filterparam).order_by("-douban_score", "-douban_counter")
        elif filtertype == "area":
            if filterparam == "其它":
                # 空的集合
                movie_list = Movie.objects.none()
                for area in movie_area:
                    movie_list_area = Movie.objects.filter(country__contains=area)
                    # 合并集合
                    movie_list = movie_list | movie_list_area
                movie_list = movie_list.order_by("-douban_score", "-douban_counter")
            else:
                movie_list = Movie.objects.filter(country__contains=filterparam).order_by("-douban_score", "-douban_counter")
        elif filtertype == "year":
            # 过滤上映日期
            if filterparam == "20":
                movie_list = Movie.objects.filter(dateyear__lte="2002-12-30").order_by("-douban_score", "-douban_counter")
            else:
                movie_list = Movie.objects.filter(dateyear__contains=filterparam).order_by("-douban_score", "-douban_counter")
    # 没有登录用户
    else:
        movie_list = Movie.objects.all().order_by("-douban_score", "-douban_counter")
        if filtertype == "style":
            movie_list = Movie.objects.filter(style__contains=filterparam).order_by("-douban_score", "-douban_counter")
        elif filtertype == "area":
            if filterparam == "其它":
                # 空的集合
                movie_list = Movie.objects.none()
                for area in movie_area:
                    movie_list_area = Movie.objects.filter(country__contains=area)
                    # 合并集合
                    movie_list = movie_list | movie_list_area
                movie_list = movie_list.order_by("-douban_score", "-douban_counter")
            else:
                movie_list = Movie.objects.filter(country__contains=filterparam).order_by("-douban_score", "-douban_counter")
        elif filtertype == "year":
            # 过滤上映日期
            if filterparam == "20":
                movie_list = Movie.objects.filter(dateyear__lte="2002-12-30").order_by("-douban_score", "-douban_counter")
            else:
                movie_list = Movie.objects.filter(dateyear__contains=filterparam).order_by("-douban_score", "-douban_counter")

    # 进行分页,每页12个Movie实例
    paginator = Paginator(movie_list, 12)
    try:
        movielist = paginator.page(page)
    # 页面号码是无效的还是超过最大页码的情况,默认都是第一页.
    except (EmptyPage, InvalidPage, PageNotAnInteger):
        movielist = paginator.page(1)

    context = {"movielist":movielist,
               "type":choice_type,
               "action":action,
               "filtertype":filtertype,
               "filterparam":filterparam,}
    
    # 默认不分页.
    is_paginated = False
    # 总页码数量大于2的情况下,需要分页.
    if paginator.num_pages > 1:
        is_paginated = True
    # 当前页码.
    page_number = movielist.number
    # 获取到整个分页页码列表,比如分了4页,那么就是[1,2,3,4]
    page_range = paginator.page_range
    total_pages = paginator.num_pages
    # 获取了各种参数.
    data = pagination_data(page_number, page_range, total_pages, is_paginated)
    # 更新参数字典. 
    context.update(data)
    return render(request, "movie/allfilms.html", context=context)

def get_latest_movielist(request):
    """
    获取最新的电影列表
    """
    # 为了区别网页上用户选择的选项块.
    action = "getmovielist"
    choice_type = "latest"
    # 获取用户请求页的页码,例如:?page=12.
    page = request.GET.get("page")
    if page is not None:
        page = int(page)
    else:
        page = 1
    filtertype = request.GET.get("filtertype")
    filterparam = request.GET.get("filterparam")
    # 根据时间排序,排除了不能播放的电影
    if filtertype == "style":
        movie_list = Movie.objects.filter(style__contains=filterparam,
                                          movie_address__isnull=False).order_by("-dateyear")
    elif filtertype == "area":
        if filterparam == "其它":
            # 空的集合
            movie_list = Movie.objects.none()
            for area in movie_area:
                movie_list_area = Movie.objects.filter(country__contains=area)
                # 合并集合
                movie_list = movie_list | movie_list_area
            movie_list = movie_list.order_by("-dateyear")
        else:
            movie_list = Movie.objects.filter(country__contains=filterparam, 
                                              movie_address__isnull=False).order_by("-dateyear")
    elif filtertype == "year":
        if filterparam == "20":
            movie_list = Movie.objects.filter(dateyear__lte="2002-12-30", 
                                              movie_address__isnull=False).order_by("-dateyear")
        else:
            movie_list = Movie.objects.filter(dateyear__contains=filterparam, 
                                              movie_address__isnull=False).order_by("-dateyear")
    else:
        # 默认什么选项都没有的情况下,电影列表就是按照时间排序
        movie_list = Movie.objects.filter(movie_address__isnull=False).order_by("-dateyear")
        # 查询没有download_link的电影名称.
        # listc = []
        # movie_list = Movie.objects.filter(download_link="NULL")
        # for listb in movie_list: 
        #     listc.append(listb.movie_name)
        # list_str = "\n".join(listc)
        # print "List is : ", list_str
        # with open("/home/xiaoguai/movie_name.txt", "w") as f:
        #     f.write(list_str.encode("utf-8"))
    
    # 进行分页,每页12个Movie实例
    paginator = Paginator(movie_list, 12)
    try:
        movielist = paginator.page(page)
    # 页面号码是无效的还是超过最大页码的情况,默认都是第一页.
    except (EmptyPage, InvalidPage, PageNotAnInteger):
        movielist = paginator.page(1)

    context = {"movielist":movielist,
               "type":choice_type,
               "action":action,
               "filtertype":filtertype,
               "filterparam":filterparam,}
    
    # 默认不分页.
    is_paginated = False
    # 总页码数量大于2的情况下,需要分页.
    if paginator.num_pages > 1:
        is_paginated = True
    # 当前页码.
    page_number = movielist.number
    # 获取到整个分页页码列表,比如分了4页,那么就是[1,2,3,4]
    page_range = paginator.page_range
    total_pages = paginator.num_pages
    # 获取了各种参数.
    data = pagination_data(page_number, page_range, total_pages, is_paginated)
    # 更新参数字典. 
    context.update(data)
    return render(request, "movie/allfilms.html", context=context)

def get_filmfest_list(request):
    """
    获取参加电影节的电影列表
    """
    # 为了区别网页上用户选择的选项块.
    action = "getmovielist"
    choice_type = "festival"
    # 获取用户请求页的页码,例如:?page=12.
    page = request.GET.get("page")
    if page is not None:
        page = int(page)
    else:
        page = 1
    filtertype = request.GET.get("filtertype")
    filterparam = request.GET.get("filterparam")
    # 过滤有带'节'的字段电影列表,并且能播放
    moviequery = Movie.objects.filter(movie_address__isnull=False, dateyear__contains="节")
    if filtertype == "style":
        movie_list = moviequery.filter(style__contains=filterparam).order_by("-douban_score", "-douban_counter")
    elif filtertype == "area":
        if filterparam == "其它":
            # 空的集合
            movie_list = Movie.objects.none()
            for area in movie_area:
                movie_list_area = Movie.objects.filter(country__contains=area)
                # 合并集合
                movie_list = movie_list | movie_list_area

templates/movie/movie.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load movie_tags %}

{% block title %} 电影池 {% endblock title %}
{% block head %}
    <link href="{% static 'movie/css/index.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <script src="{% static 'movie/js/movies.js' %}"></script>
{% endblock head %}

{% block page_content %}
    <div id="mainbody" class="moviebody">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="movieList">

                        <ul class="movieList_tab">
                            <li {% if type == 'suggest' %} class="current" {% endif %}>
                                <a href="{% url 'movie:playmostmovies' %}"> {% trans '热播电影' %}</a></li>
                            <li {% if type == 'festival' %} class="current" {% endif %} >
                                <a href="{% url 'movie:good_evaluationmovies' %}">本周口碑榜</a></li>
                            <li {% if type == 'latest' %} class="current" {% endif %}>
                                <a href="{% url 'movie:box_officemovies' %}">北美票房榜</a></li>
                        </ul>

                        <ul class="movieTab_con">
                            <!--选项卡切换之最新-->
                            <li class="current">
                               <div class="movieList_con row">
                                    <div class="col-md-4">
                                        <div class="movieList_con_cell">
                                            <div class="thumbnail movieList_con_cell_info">
                                                <span class="glyphicon glyphicon-star havesee"></span>
                                                <div class="post-thumbnail">
                                                <a href="{{ movie.douban_link }}" class="inimg" target="_blank" title="{{ movie.movie_name }}">
                                                    <img src="{{ movie.image }}" alt="{{ movie.movie_name }}"/>
                                                </a>
                                                    <div class="img_title" style="display:none">
                                                        <small class="imdbscore">{{ movie.style }}</small><br>
                                                        <small class="imdbscore">{{ movie.dateyear }}</small>
                                                    </div>
                                                </div>
                                                <div class="caption movie-info">
                                                    <ul class="title"><a target="_blank" href="http://baike.baidu.com/item/{{ movie.movie_name }}">{{ movie.movie_name|slice:"13" }}</a></ul>
                                                    <ul>
                                                        {% if movie.movie_address %}
                                                        <a href="{{ movie.movie_address }}" target="_blank" class="btn btn-primary btn-sm btn-movie" role="button" id="{{ movie.id }}">播放</a>
                                                        {% endif %}
                                                        {% if movie.download_link %}
                                                        <a href="{{ movie.download_link }}" target="_blank" class="btn btn-primary btn-sm" role="button">下载</a>
                                                        {% endif %}
                                                    </ul>
                                                    <ul class="title">
                                                        <li>
                                                            {% ifequal movie.country '' %}top250{% endifequal %}{{ movie.country }}<br>
                                                            <span class="wpfp-span">豆瓣评分:{{ movie.douban_score }}</span>
                                                        </li>                                          
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>           
                </div>
                <!--排行榜开始-->
                <div class="col-md-2">
                    <div class="rankBar">
                        <h5 class="rankBar_title">
                            热播电影
                        </h5>
                        {% get_play_most_movies as play_most_movies %}
                        <ul class="rankBar_list">
                            {% for movie in play_most_movies %}
                                <li><a href="{% url 'movie:movie' movie.pk %}">{{ movie.movie_name }}</a></li>
                            {% empty %}
                            暂时没有电影
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rankBar">
                        <h5 class="rankBar_title">
                            本周口碑榜
                        </h5>
                        {% get_good_evaluation_movies as good_evaluation_movies %}
                        <ul class="rankBar_list">
                            {% for movie in good_evaluation_movies %}
                                <li><a href="{% url 'movie:movie' movie.pk %}">{{ movie.movie_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rankBar">
                        <h5 class="rankBar_title">
                            北美票房榜
                        </h5>
                        {% get_box_office_movies as box_office_movies %}
                        <ul class="rankBar_list">
                            {% for movie in box_office_movies %}
                                <li><a href="{% url 'movie:movie' movie.pk %}">{{ movie.movie_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!--排行榜结束-->
            </div>
        </div>
    </div>
{% endblock page_content %}


 

templates/movie/ranking_list.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load movie_tags %}

{% block title %} 电影池 {% endblock title %}
{% block head %}
    <link href="{% static 'movie/css/index.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <script src="{% static 'movie/js/movies.js' %}"></script>
{% endblock head %}

{% block page_content %}
    <div id="mainbody" class="moviebody">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="movieList">

                        <ul class="movieList_tab">
                            <li {% if type == 'playmostmovies' %} class="current" {% endif %}>
                                <a href="{% url 'movie:playmostmovies' %}"> {% trans '热播电影' %}</a></li>
                            <li {% if type == 'good_evaluationmovies' %} class="current" {% endif %} >
                                <a href="{% url 'movie:good_evaluationmovies' %}">{% trans '本周口碑榜' %}</a></li>
                            <li {% if type == 'box_officemovies' %} class="current" {% endif %}>
                                <a href="{% url 'movie:box_officemovies' %}">北美票房榜</a></li>
                        </ul>

                        <ul class="movieTab_con">
                            <!--选项卡切换之最新-->
                            <li class="current">
                                <div class="movieList_con row">
                                    {% for movie in movielist %}
                                    <div class="col-md-4">
                                        <div class="movieList_con_cell">
                                            <div class="thumbnail movieList_con_cell_info">
                                                <span class="glyphicon glyphicon-star havesee"></span>
                                                <div class="post-thumbnail">
                                                <a href="{{ movie.douban_link }}" class="inimg" target="_blank" title="{{ movie.movie_name }}">
                                                    <img src="{{ movie.image }}" alt="{{ movie.movie_name }}"/>
                                                </a>
                                                    <div class="img_title" style="display:none">
                                                        <small class="imdbscore">{{ movie.style }}</small><br>
                                                        <small class="imdbscore">{{ movie.dateyear }}</small>
                                                    </div>
                                                </div>
                                                <div class="caption movie-info">
                                                    <ul class="title"><a target="_blank" href="http://baike.baidu.com/item/{{ movie.movie_name }}">{{ movie.movie_name|slice:"13" }}</a></ul>
                                                    <ul>
                                                        {% if movie.movie_address %}
                                                        <a href="{{ movie.movie_address }}" target="_blank" class="btn btn-primary btn-sm btn-movie" role="button" id="{{ movie.id }}">播放</a>
                                                        {% endif %}
                                                        {% if movie.download_link %}
                                                        <a href="{{ movie.download_link }}" target="_blank" class="btn btn-primary btn-sm" role="button">下载</a>
                                                        {% endif %}
                                                    </ul>
                                                    <ul class="title">
                                                        <li>
                                                            {% ifequal movie.country '' %}top250{% endifequal %}{{ movie.country }}<br>
                                                            <span class="wpfp-span">豆瓣评分:{{ movie.douban_score }}</span>
                                                        </li>                                          
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </li>
                        </ul>
                    </div>           
                </div>
                <!--排行榜开始-->
                <div class="col-md-2">
                    <div class="rankBar">
                        <h5 class="rankBar_title">
                            热播电影
                        </h5>
                        {% get_play_most_movies as play_most_movies %}
                        <ul class="rankBar_list">
                            {% for movie in play_most_movies %}
                                <li><a href="{% url 'movie:movie' movie.pk %}">{{ movie.movie_name }}</a></li>
                            {% empty %}
                            暂时没有电影
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rankBar">
                        <h5 class="rankBar_title">
                            本周口碑榜
                        </h5>
                        {% get_good_evaluation_movies as good_evaluation_movies %}
                        <ul class="rankBar_list">
                            {% for movie in good_evaluation_movies %}
                                <li><a href="{% url 'movie:movie' movie.pk %}">{{ movie.movie_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rankBar">
                        <h5 class="rankBar_title">
                            北美票房榜
                        </h5>
                        {% get_box_office_movies as box_office_movies %}
                        <ul class="rankBar_list">
                            {% for movie in box_office_movies %}
                                <li><a href="{% url 'movie:movie' movie.pk %}">{{ movie.movie_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!--排行榜结束-->
            </div>
        </div>
    </div>
{% endblock page_content %}


 