blog/urls.py
#coding:utf-8

from django.conf.urls import url
import views

# app_name是为了reverse函数准备的
app_name = "blog"
# ^$代表了空字符串
urlpatterns = [
    url(r'^blog/$', views.IndexView.as_view(), name="index"),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^blog/archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name="archives"),
    url(r'^blog/category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^blog/tag/(?P<pk>[0-9]+)/$', views.TagViews.as_view(), name="tag"),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('webuser.urls')),
    url(r'', include('movie.urls')),
    url(r'', include('questions.urls')),
    url(r'', include('webchat.urls')),
    url(r'', include('weixin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "questions"
# ^$代表了空字符串
urlpatterns = [
    url(r'^questions/$', views.questions, name="questions"),
    url(r'^questions/unanswered_questions$', views.unanswered_questions, name="unanswered_questions"),
    url(r'^questions/answered_questions$', views.answered_questions, name="answered_questions"),
    url(r'^questions/(?P<questionid>[0-9]+)/$', views.question, name="question"),
    url(r'^questions/ask/$', views.ask, name="ask"),
    url(r'^questions/answer/(?P<questionid>[0-9]+)/$', views.answer, name="answer"),
    url(r'^questions/answer/accept/$', views.accept, name="accept"),
    url(r'^questions/answer/vote/$', views.vote, name="vote"),
    url(r'^questions/favorite/$', views.favorite, name="favorite"),
]

webuser/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "webuser"
# ^$代表了空字符串
urlpatterns = [
    url(r'^$', views.index, name="webuser_index"),
    url(r'^weblogin/$', views.web_login, name="webuser_login"),
    url(r'^register/$', views.register, name="webuser_register"),
    url(r'^settings/$', views.settings, name="webuser_settings"),
    url(r'^settings/picture/$', views.picture, name="webuser_picture"),
    url(r'^settings/upload_picture/$', views.upload_picture, name="upload_picture"),
    url(r'^settings/save_uploaded_picture/$', views.save_uploaded_picture, name="save_uploaded_picture"),
    url(r'^settings/addfriends/$', views.addfriends, name="addfriends"),
    url(r'^webuser/concern_issues/$', views.concern_issues, name="concern_issues"),    # 关注的问题
    url(r'^webuser/my_questions/$', views.my_questions, name="my_questions"),    # 用户提的问题
    url(r'^webuser/my_answer/$', views.my_answer, name="my_answer"),    # 用户的回答
    url(r'^webuser/changepassword/$', views.change_password, name="webuser_password"),
    url(r'^webuser/changeemail/$', views.change_email, name="webuser_email"),
    url(r'^webuser/getuserinfo/(?P<userid>[0-9]+)/$', views.getuserinfo, name="getuserinfo"),
    url(r'^weblogout/$', auth_views.logout, {"next_page":"/"}, name="webuser_logout"),
]

questions/forms.py
#coding:utf-8

from django import forms

from models import Question, Tag, Answer

class QuestionForm(forms.ModelForm):
    """
    提问题的表单.
    """
    STYLE_CHOICE = ((u"1", u"动作"), (u"2", u"悬疑"), (u"3", u"爱情"), (u"4", u"科幻"), 
                    (u"5", "恐怖"), (u"6", "喜剧"), (u"7", u"其它"))
    tag = forms.MultipleChoiceField(choices=STYLE_CHOICE,
                                    widget=forms.CheckboxSelectMultiple(),
                                    required=False,
                                    label="标签")

    class Meta:
        model = Question
        fields = ["title", "description", "tag"]
        widgets = {
            "title":forms.TextInput(attrs={"class":"form-control"}),
            "description":forms.Textarea(attrs={"class":"form-control"})
        }
        labels = {
            "title":"问题简述",
            "description":"问题详细描述"
        }

class AnswerForm(forms.ModelForm):
    """
    回答问题的表单
    """ 
    answercontent = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control", "rows":"4"}),
                                    max_length=3000)
    
    class Meta:
        model = Answer
        fields = ["answercontent"]

questions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseForbidden
from django.db.models import Q

from .models import Question, Tag, Answer, Activity
from .forms import QuestionForm, AnswerForm
from blog.utils import pagination_data

import sys

def questions(request):
    """
    展现所有问题的视图函数.
    """
    return all(request)

def question(request, questionid):
    """
    单个问题的视图函数.
    """
    action = "questions"
    source = request.GET.get("source")
    if source == None:
        source = "my_answer"
    question = get_object_or_404(Question, pk=questionid)
    form = AnswerForm(instance=question)
    
    context = {"question":question,
               "action":action,
               "form":form,
               "source":source}
    return render(request, "questions/question.html", context=context)
    
def all(request):
    """
    所有问题列表视图函数.
    """
    questions = Question.objects.all()
    return _questions(request, questions, "all")

def unanswered_questions(request):
    """
    未采纳问题列表的视图函数.
    """
    questions = Question.get_unanswered()
    return _questions(request, questions, "unanswered")

def answered_questions(request):
    """
    采纳问题列表的视图函数.
    """
    questions = Question.get_answered()
    return _questions(request, questions, "answered")

def _questions(request, questions, active):
    action = "questions"
    source = "questions_list"

    paginator = Paginator(questions, 10)
    page = request.GET.get("page")
    if page is not None:
        page = int(page)
    else:
        page = 1
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        # page的数目超过了最大页数,遇到这种情况会返回最后一页的数据给用户
        questions = paginator.page(paginator.num_pages)

    context = {"questions":questions,
               "active":active,
               "action":action,
               "source":source}
    
    # 默认不分页.
    is_paginated = False
    # 总页码数量大于2的情况下,需要分页.
    if paginator.num_pages > 1:
        is_paginated = True
    # 当前页码.
    page_number = questions.number
    # 获取到整个分页页码列表,比如分了4页,那么就是[1,2,3,4]
    page_range = paginator.page_range
    total_pages = paginator.num_pages
    # 获取了各种参数.
    data = pagination_data(page_number, page_range, total_pages, is_paginated)
    # 更新参数字典. 
    context.update(data)
    return render(request, "questions/questions.html", context=context)

@login_required
def ask(request):
    reload(sys)
    sys.setdefaultencoding("utf-8")
    action = "questions"
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = Question()
            question.user = request.user
            question.title = form.cleaned_data.get("title")
            question.description = form.cleaned_data.get("description")
            tag_id_list = form.cleaned_data.get("tag")
            # 只有先保存了question对象,才能关联tag
            question.save()
            print "type and tag:", type(tag_id_list),tag_id_list
            for tag_id in tag_id_list:
                tag = Tag.objects.get(id=int(tag_id))
                question.tag.add(tag)
            return redirect("/questions/")
        else:
            return render(request, "questions/ask.html", {"form":form, "action":action})
    else:
        form = QuestionForm()
    return render(request, "questions/ask.html", {"form":form, "action":action})

@login_required
def answer(request, questionid):
    """
    发送答案的视图函数.
    """
    question = get_object_or_404(Question, pk=questionid)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = Answer()
            answer.user = request.user
            answer.question = question
            answer.answer_content = form.cleaned_data.get("answercontent")
            print "answer.question:", answer.question
            answer.save()
            #
            answer.user.webuser.notify_answered(answer.question)
            return redirect(u"/questions/{0}/?source=questions_list".format(answer.question.pk))
        else:
            return render(request, "questions/question.html", {"question":question, "form":form})
    else:
        return redirect("/questions/")

@login_required
def accept(request):
    """
    问题提问者接受答案的视图函数.
    """
    answer_id = request.POST["answer"]
    answer = Answer.objects.get(pk=answer_id)
    user = request.user
    # 通知用户的答案被接受
    #
    # 如果当前的用户是提出该问题的用户,可以将答案设置成接受.
    if user == answer.question.user:
        answer.accept()
        return HttpResponse()
    else:
        return HttpResponseForbidden()

@login_required
def vote(request):
    """
    用户投票的视图函数.
    """
    answer_id = request.POST["answer"]
    answer = Answer.objects.get(pk=answer_id)
    # "R","U","D"
    vote = request.POST["vote"]
    user = request.user
    # 在所有的动作中,获取到该答案的作者,答案id,以及他的vote activity
    activity = Activity.objects.filter(
        Q(activity_type=Activity.UP_VOTE) | Q(activity_type=Activity.DOWN_VOTE),
        user=user, 
        answer=answer_id)
    # 如果该用户有给这个答案投票的行为的话,就进行删除
    if activity:
        activity.delete()
    if vote in [Activity.UP_VOTE, Activity.DOWN_VOTE]:
        # 保存这次的投票行为.
        activity = Activity(activity_type=vote, user=user, answer=answer_id)
        activity.save()
    return HttpResponse(answer.calculate_votes())

@login_required
def favorite(request):
    """
    用户关注问题的视图函数.
    """
    question_id = request.POST["question"]
    question = Question.objects.get(pk=question_id)
    user = request.user
    # 获取该用户关注的行为.
    activity = Activity.objects.filter(activity_type=Activity.FAVORITE, user=user, question=question_id)
    if activity:
        activity.delete()
    else:
        # 没有该行为就创建该行为.
        activity = Activity(activity_type=Activity.FAVORITE, user=user, question=question_id)
        activity.save()
    return HttpResponse(question.calculate_favorite())

templates/questions/ask.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load static %}

{% block title %} 提交问题 {% endblock title %}
{% block head %}
    <link href="{% static 'questions/css/questions.css' %}" rel="stylesheet">
{% endblock %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'questions:questions' %}">{% trans "找电影" %}</a></li>
            <li class="active">{% trans "提问" %}</li>
        </ol>

        <form action="{% url 'questions:ask' %}" method="post" class="form-horizontal" role="form">
        {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                    {% if field.label == '问题详细描述' %}
                        {% include 'questions/markdown_editor.html' with textarea='id_description' %}
                    {% endif %}
                    {{ field }}
                    {% if field.help_text %}
                        <span class="help-block">{{ field.help_text }}</span>
                    {% endif %}
                    {% for error in field.errors %}
                        <label class="control-label">{{ error }}</label>
                    {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-large btn-primary">{% trans '提交问题' %}</button>
                    <a href="{% url 'questions:questions' %}" class="btn btn-large btn-default">{% trans '取消提问' %}</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock page_content %}

templates/questions/markdown_editor.html
{% load staticfiles %}
<script src="{% static 'questions/js/jquery.selection.js' %}"></script>
<script src="{% static 'questions/js/nomovie.markdown.js' %}"></script>

<div class="markdown">
    <div class="modal fade" id="markdown_insert_link">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Insert Link</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="markdown_link_text" class="control-label">Link Text</label>
                        <input type="text" class="form-control" id="markdown_link_text" placeholder="Link Text">
                    </div>
                    <div class="form-group">
                        <label for="markdown_url" class="control-label">URL</label>
                        <input type="text" class="form-control" id="markdown_url" placeholder="URL">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary add_link" data-dismiss="modal">Ok</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="markdown_insert_picture">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Insert Image</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="markdown_picture_url" class="control-label">Picture URL</label>
                        <input type="text" class="form-control" id="markdown_picture_url" placeholder="Picture URL">
                    </div>
                    <div class="form-group">
                        <label for="markdown_alt_text" class="control-label">Alt Text</label>
                        <input type="text" class="form-control" id="markdown_alt_text" placeholder="Alt Text">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary add_picture" data-dismiss="modal">Ok</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="markdown_help">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">帮助</h4>
                </div>
                <div class="modal-body">
                    <p>你可以访问这个网站来学习<a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">用力戳</a>.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
    <div class="btn-group">
        <button type="button" class="btn btn-default btn-sm" ref="header"><span class="glyphicon glyphicon-header"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="bold"><span class="glyphicon glyphicon-bold"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="italic"><span class="glyphicon glyphicon-italic"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="list"><span class="glyphicon glyphicon-list"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="link"><span class="glyphicon glyphicon-link"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="picture"><span class="glyphicon glyphicon-picture"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="indent-left"><span class="glyphicon glyphicon-indent-left"></span></button>
        <button type="button" class="btn btn-default btn-sm" ref="indent-right"><span class="glyphicon glyphicon-indent-right"></span></button>
    </div>
    <button type="button" data-toggle="modal" data-target="#markdown_help" class="btn btn-link btn-sm pull-right"><span class="glyphicon glyphicon-question-sign"></span>帮助</button>
</div>
<script>$(function(){$("#{{ textarea }}").markdown();});</script>

templates/questions/paginator.html
<ul class="pagination">
    {% if paginator.has_previous %}
        <li><a href="?page={{ paginator.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    
    {% if first %}
        <!-- 判断是否显示第一页的页码号 -->
        <li><a href="?page=1">1</a></li>
    {% endif %}
    {% if left %}
        {% if left_has_more %}
            <!-- 判断是否显示第一页前的省略号 -->
            <li><a>.....</a></li>
        {% endif %}
        {% for i in left %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
    {% endif %}
    <!-- 当前页 -->
    <li class="active"><span>{{ paginator.number }} <span class="sr-only">(current)</span></span></li>
    {% if right %}
        {% for i in right %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if right_has_more %}
            <!-- 判断是否显示最后一页前的省略号 -->
            <li><a>.....</a></li>
        {% endif %}
    {% endif %}
    {% if last %}
        <!-- 判断是否显示最后一页的页码号 -->
        <li><a href="?page={{ paginator.paginator.num_pages }}">{{ paginator.paginator.num_pages }}</a></li>
    {% endif %}

    {% if paginator.has_next %}
        <li><a href="?page={{ paginator.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>

templates/questions/partial_answer.html
{% load i18n %}
{% load humanize %}

<div class="row answer" answer-id="{{ answer.id }}">
{% csrf_token %}
    <div class="col-md-1 options">
        <span class="glyphicon glyphicon-chevron-up vote up-vote{% if user in answer.get_up_voters %} voted{% endif %}" title="{% trans '赞成' %}"></span>
        <span class="votes">{{ answer.votes }}</span>
        <span class="glyphicon glyphicon-chevron-down vote down-vote{% if user in answer.get_down_voters %} voted{% endif %}" title="{% trans '反对' %}"></span>
        {% if answer.is_accepted and user == question.user %}
            <span class="glyphicon glyphicon-ok accept accepted" title="{% trans '不接受该答案' %}"></span>
        {% elif answer.is_accepted %}
            <span class="glyphicon glyphicon-ok accept accepted" style="cursor: default"></span>
        {% elif user == question.user %}
            <span class="glyphicon glyphicon-ok accept" title="{% trans '采纳该答案' %}"></span>
        {% endif %}
    </div>
    <div class="col-md-11">
        <div class="answer-user">
            <a><img src="{{ answer.user.webuser.get_picture }}" class="media-object img-circle" style='max-width:40px;'></a>
            <a href="{% url 'webuser:getuserinfo' answer.user.id %}" class="username">{{ answer.user.username }}</a>
            <small class="answered">{% trans "在" %} {{ answer.create_date|naturaltime }}{% trans "回答" %}</small>
        </div>
        <div class="answer-description">
            {{ answer.get_answercontent_as_markdown|safe }}
        </div>
    </div>
</div>

templates/questions/partial_question.html
{% load humanize %}

<div class="panel panel-default question" question-id="{{ question.id }}" source="{{ source }}">
    <div class="panel-heading">
        <h3 class="panel-title">
        {% if question.has_accepted_answer %}
            <span class="glyphicon glyphicon-ok"></span>
        {% endif %}
        <a>{{ question.title }}</a>
        </h3>
    </div>
    <div class="panel-body clearfix">
        <div class="question-info">
            <div class="info">
                <h5><span class="glyphicon glyphicon-comment"></span>回答</h5>
                <span>{{ question.get_answers_count }}</span>
            </div>
            <div class="info">
                <h5><span class="glyphicon glyphicon-star"></span>同求</h5>
                <span>{{ question.favorites }}</span>
            </div>
        </div>
        <div class="question-user">
            <a href="{% url 'webuser:getuserinfo' question.user.id %}"><img src="{{ question.user.webuser.get_picture }}" class="img-circle" style='max-width:40px;'></a>
            <a href="{% url 'webuser:getuserinfo' question.user.id %}" class="username">{{ question.user.username }}</a>
            <span class="asked">在{{ question.update_date|naturaltime }}提问</span>
        </div>
        <div class="question-description">
            {{ question.get_description_preview_as_markdown|safe }}
        </div>
        {% if question.tag %}
        <p>
            {% for tag in question.tag.all %}
                <span class="label label-primary">{{ tag.name }}</span>
            {% endfor %}
        </p>
        {% endif %}
    </div>
</div>

templates/questions/question.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block title %} 找电影 {% endblock title %}
{% block head %}
    <link href="{% static 'questions/css/questions.css' %}" rel="stylesheet">
    <script src="{% static 'questions/js/questions.js' %}"></script>
{% endblock %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <ol class="breadcrumb">
            {% if source == 'concern_issues' %}
                <li><a href="{% url 'webuser:webuser_settings' %}">{% trans "我的主页" %}</a></li>
                <li><a href="{% url 'webuser:concern_issues' %}">{% trans "我关注的问题" %}</a></li>
                <li class="active">{% trans "回答" %}</li>
            {% elif source == 'questions_list' %}
                <li><a href="{% url 'questions:questions' %}">{% trans "找电影" %}</a></li>
                <li class="active">{% trans "回答" %}</li>
            {% elif source == 'my_questions' %}
                <li><a href="{% url 'webuser:webuser_settings' %}">{% trans "我的主页" %}</a></li>
                <li><a href="{% url 'webuser:my_questions' %}">{% trans "我的提问" %}</a></li>
                <li class="active">{% trans "回答" %}</li>
            {% elif source == 'my_answer' %}
                <li><a href="{% url 'webuser:webuser_settings' %}">{% trans "我的主页" %}</a></li>
                <li><a href="{% url 'webuser:my_answer' %}">{% trans "我的回答" %}</a></li>
                <li class="active">{% trans "回答" %}</li>
            {% endif %}
        </ol>
        <div class="row question" question-id="{{ question.id }}">
        {% csrf_token %}
            <div class="col-md-1 options">
            {% if user in question.get_favoriters %}
                <span class="glyphicon glyphicon-star favorite favorited" title="Click to mark this question as favorite; click again to toggle"></span>
            {% else %}
                <span class="glyphicon glyphicon-star-empty favorite" title="Click to mark this question as favorite; click again to toggle"></span>
            {% endif %}
                <span class="favorite-count">{{ question.favorites }}</span>
            </div>
            <div class="col-md-11">
                <h2>{{ question.title }}</h2>
                <div class="question-user">
                    <a href="{%url 'webuser:getuserinfo' question.user.id %}"><img src="{{ question.user.webuser.get_picture }}" class="img-circle" style='max-width:40px;'></a>
                    <a href="{%url 'webuser:getuserinfo' question.user.id %}" class="username">{{ question.user.username }}</a>
                    <small class="asked">在{{ question.update_date|naturaltime }}提问</small>
                </div>
                <div class="question-description">
                    {{ question.get_description_preview_as_markdown|safe }}
                </div>              
                {% if question.tag %}
                <p>
                    {% for tag in question.tag.all %}
                        <span class="label label-primary">{{ tag.name }}</span>
                    {% endfor %}
                </p>
                {% endif %}
            </div>
        </div>
        <h4 class="page-header">回答者</h4>
        <div class="answers">
            {% for answer in question.get_answers %}
                {% include 'questions/partial_answer.html' with question=question answer=answer %}
            {% endfor %}
            <h4>您的回答</h4>
            <form action="{% url 'questions:answer' question.id %}" method="post" role="form">
            {% csrf_token %}
                {{ form.question }}
                {{ form.question.errors }}
                <div class="form-group">
                    {% include 'questions/markdown_editor.html' with textarea='id_answercontent' %}
                    {{ form.answercontent }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn brn-large btn-primary">{% trans "提交答案"%}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock page_content %}

templates/questions/questions.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load static %}

{% block title %} 找电影 {% endblock title %}
{% block head %}
    <link href="{% static 'questions/css/questions.css' %}" rel="stylesheet">
    <script src="{% static 'questions/js/questions.js' %}"></script>
{% endblock %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <div class="header">
            {% if request.user.is_authenticated %}
                <a href="{% url 'questions:ask' %}" class="btn btn-primary pull-right">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> {% trans "我要找电影" %}
                </a>
            {% else %}
                <a href="{% url 'webuser:webuser_login' %}" class="btn btn-primary pull-right">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> {% trans "提问题，请登录" %}
                </a>
            {% endif %}
            <h2><small>{% trans "找电影问答列表" %}</small></h2>
        </div>

        <div class="questions">
            <ul class="nav nav-tabs">
                <li role="presentation" {% if active == 'all' %} class="active"{% endif %}><a href="{% url 'questions:questions' %}">{% trans '全部'%}</a> </li>
                <li {% if active == 'answered' %} class="active"{% endif %} role="presentation" ><a href="{% url 'questions:answered_questions' %}">{% trans '已采纳' %}</a> </li>
                <li role="presentation" {% if active == 'unanswered' %} class="active"{% endif %}><a href="{% url 'questions:unanswered_questions' %}">{% trans '未采纳' %}</a> </li>
            </ul>

            {% for question in questions %}
                {% include 'questions/partial_question.html' with question=question source=source %}
            {% empty %}
                <h4 class="no-data">{% trans "目前没有问题." %}</h4>
            {% endfor %}
            {% include 'questions/paginator.html' with paginator=questions %}
        </div>
    </div>
</div>
{% endblock page_content %}