blog/urls.py
#coding:utf-8

from django.conf.urls import url
import views

# app_name是为了reverse函数准备的
app_name = "blog"
# ^$代表了空字符串
urlpatterns = [
    url(r'^blog/$', views.IndexView.as_view(), name="index"),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^blog/archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name="archives"),
    url(r'^blog/category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^blog/tag/(?P<pk>[0-9]+)/$', views.TagViews.as_view(), name="tag"),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('webuser.urls')),
    url(r'', include('movie.urls')),
    url(r'', include('questions.urls')),
    url(r'', include('webchat.urls')),
    url(r'', include('weixin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "questions"
# ^$代表了空字符串
urlpatterns = [
    url(r'^questions/$', views.questions, name="questions"),
    url(r'^questions/unanswered_questions$', views.unanswered_questions, name="unanswered_questions"),
    url(r'^questions/answered_questions$', views.answered_questions, name="answered_questions"),
    url(r'^questions/(?P<questionid>[0-9]+)/$', views.question, name="question"),
    url(r'^questions/ask/$', views.ask, name="ask"),
    url(r'^questions/answer/(?P<questionid>[0-9]+)/$', views.answer, name="answer"),
    url(r'^questions/answer/accept/$', views.accept, name="accept"),
    url(r'^questions/answer/vote/$', views.vote, name="vote"),
    url(r'^questions/favorite/$', views.favorite, name="favorite"),
]

webuser/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "webuser"
# ^$代表了空字符串
urlpatterns = [
    url(r'^$', views.index, name="webuser_index"),
    url(r'^weblogin/$', views.web_login, name="webuser_login"),
    url(r'^register/$', views.register, name="webuser_register"),
    url(r'^settings/$', views.settings, name="webuser_settings"),
    url(r'^settings/picture/$', views.picture, name="webuser_picture"),
    url(r'^settings/upload_picture/$', views.upload_picture, name="upload_picture"),
    url(r'^settings/save_uploaded_picture/$', views.save_uploaded_picture, name="save_uploaded_picture"),
    url(r'^settings/addfriends/$', views.addfriends, name="addfriends"),
    url(r'^webuser/concern_issues/$', views.concern_issues, name="concern_issues"),    # 关注的问题
    url(r'^webuser/my_questions/$', views.my_questions, name="my_questions"),    # 用户提的问题
    url(r'^webuser/my_answer/$', views.my_answer, name="my_answer"),    # 用户的回答
    url(r'^webuser/changepassword/$', views.change_password, name="webuser_password"),
    url(r'^webuser/changeemail/$', views.change_email, name="webuser_email"),
    url(r'^webuser/getuserinfo/(?P<userid>[0-9]+)/$', views.getuserinfo, name="getuserinfo"),
    url(r'^weblogout/$', auth_views.logout, {"next_page":"/"}, name="webuser_logout"),
]

webuser/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings as django_settings

from questions.models import Notification

import urllib, os

class Webuser(models.Model):
    """
    该数据库表格保存了用户个人的信息以及是否在线等数据
    """
    user = models.OneToOneField(User)
    location = models.CharField(max_length=50, null=True, blank=True)
    url = models.CharField(max_length=50, null=True, blank=True)
    likesstyle = models.CharField(max_length=50, null=True, blank=True)
    job_title = models.CharField(max_length=50, null=True, blank=True)
    registerday = models.DateTimeField(auto_now=True, blank=True)
    sex = models.IntegerField(default=1)
    friends = models.ManyToManyField("self")
    online = models.IntegerField(default=False)

    def __unicode__(self):
        return self.user.username

    def get_picture(self):
        """
        获取到该用户的头像
        """
        # 默认头像
        no_picture = django_settings.MEDIA_URL+"webuser_pictures/user.png"
        try:
            # 获取到头像的路径以及文件名
            filename = django_settings.MEDIA_ROOT+"/webuser_pictures/"+self.user.username+".jpg"
            # 获取到头像的url
            picture_url = django_settings.MEDIA_URL+"webuser_pictures/"+self.user.username+".jpg"
            if os.path.isfile(filename):
                return picture_url
            else:
                return no_picture
        except Exception as e:
            return no_picture

    def notify_answered(self, question):
        """
        """
        if self.user != question.user:
            Notification(
                notification_type=Notification.ANSWERED,
                from_user=self.user,
                to_user=question.user,
                question=question
            ).save()

webuser/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings as django_settings

from forms import LoginForm, SignUpForm, ProfileForm, ChangePasswordForm, ChangeEmailForm
from questions.models import Activity, Question, Answer
from blog.utils import pagination_data
from models import Webuser
from PIL import Image
import os, json, re

def index(request):
    """
    首页的视图函数.
    """
    user = request.user
    action = "webuser"
    print "user:",user
    return render(request, "webuser/index.html", locals())

def web_login(request):
    """
    用户登录的视图函数.
    """
    # 如果用户认证过,重定向到首页
    if request.user.is_authenticated():
        return redirect("/")
    if request.method == "POST":
        # 用户提交的数据存在request.POST中,这是一个类字典对象.
        # 我们利用这些数据构造了LoginForm的实例,这样Django的表单就生成了.
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            login(request, user)
            return render(request, "webuser/personal.html")
        else:
            return render(request, "webuser/login.html", {"form":form})
    # 如果不是提交数据的request,就需要转到登录界面
    else:
        return render(request, "webuser/login.html", {"form":LoginForm()})

def register(request):
    """
    用户注册的视图函数.
    """
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if not form.is_valid():
            return render(request, "webuser/register.html", {"form":form})
        else:
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            # 创建用户
            User.objects.create_user(username=username, password=password, email=email)
            # 获取到刚刚创建的用户
            user = authenticate(username=username, password=password)
            # 为新用户创建一个该用户的设置表
            webuser = Webuser(user=user)
            webuser.save()
            # 用户登录
            login(request, user)
            return redirect("/")
    else:
        return render(request, "webuser/register.html", {"form":SignUpForm()})

@login_required
def settings(request):
    """
    个人资料视图函数.
    """
    # 获取用户
    user = request.user
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            # 为wenuser对象属性添加数据
            webuser = Webuser.objects.get(user=user)
            webuser.job_title = form.cleaned_data.get("job_title")
            webuser.location = form.cleaned_data.get("location")
            webuser.url = form.cleaned_data.get("url")
            webuser.likesstyle = form.cleaned_data.get("likestyle")
            webuser.sex = form.cleaned_data.get("sex")
            # 保存数据
            webuser.save()
            # 直接为该页面发送消息
            messages.add_message(request, messages.SUCCESS, "您的资料已经编辑成功.")
    else:
        form = ProfileForm(instance=user,
                           initial={
                               "job_title":user.webuser.job_title,
                               "url":user.webuser.url,
                               "location":user.webuser.location,
                               "sex":user.webuser.sex,
                               "likestyle":user.webuser.likesstyle
                           })
    return render(request, "webuser/person_home_page_info.html", {"form":form})

@login_required
def change_password(request):
    """
    用户修改密码的视图函数
    """
    user = request.user
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get("new_password")
            # 设置新密码
            user.set_password(new_password)
            user.save()
            # 更改密码后,需要用户再次登录
            login(request, user)
            messages.add_message(request, messages.SUCCESS, "您的密码修改成功.")
    else:
        form = ChangePasswordForm(instance=user)
    return render(request, "webuser/change_password.html", {"form":form})

@login_required
def change_email(request):
    """
    用户修改邮箱的视图函数.
    """
    user = request.user
    if request.method == "POST":
        form = ChangeEmailForm(request.POST)
        if form.is_valid():
            new_email = form.cleaned_data.get("new_email")
            # 设置新邮箱
            user.email = new_email
            # 只更新email字段
            user.save(update_fields=["email"])
            messages.add_message(request, messages.SUCCESS, "您的邮箱修改成功.")
    else:
        form = ChangeEmailForm(instance=user)
    return render(request, "webuser/change_email.html", {"form":form})

@login_required
def picture(request):
    uploaded_picture= False
    # 说明头像已经上传到了服务器
    if request.GET.get("upload_picture") == "uploaded":
        uploaded_picture= True
    context = {"uploaded_picture":uploaded_picture,
               "MEDIA_URL":django_settings.MEDIA_URL}
    return render(request, "webuser/picture.html", context=context)

@login_required
def upload_picture(request):
    """
    上传头像的视图函数
    """
    try:
        # 获取到头像存放目录的路径
        webuser_picture = django_settings.MEDIA_ROOT+"/webuser_pictures/"
        # 上传的文件
        f = request.FILES["picture"]
        # 文件名
        filename = webuser_picture+request.user.username+"_tmp.jpg"
        # 写入到filename,把上传的文件用二进制的方式写入
        with open(filename, "wb+") as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        # 打开图片
        im = Image.open(filename)
        width,height = im.size
        if width > 350:
            new_width = 350
            new_height = (height*350)/width
            new_size = new_width,new_height
            # 重新设定号新的头像(抗锯齿)
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)
        # 最后重定向到头像页面,给一个参数说明头像已经上传.
        return redirect("/settings/picture/?upload_picture=uploaded")
    except Exception as e:
        return redirect("/settings/picture/")

@login_required
def save_uploaded_picture(request):
    """
    保存用户上传的头像,用户可以根据上传的头像裁剪自己想要的头像.
    """
    try:
        # 获取宽高参数
        x = int(request.POST.get("x"))
        y = int(request.POST.get("y"))
        w = int(request.POST.get("w"))
        h = int(request.POST.get("h"))
        tmp_filename = django_settings.MEDIA_ROOT+"/webuser_pictures/"+request.user.username+"_tmp.jpg"
        filename = django_settings.MEDIA_ROOT+"/webuser_pictures/"+request.user.username+".jpg"
        im = Image.open(tmp_filename)
        # 根据参数裁剪头像
        cropped_im = im.crop((x, y, w+x, h+y))
        # 缩放头像
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        # 删除临时头像文件
        os.remove(tmp_filename)
    except Exception as e:
        pass
    return redirect("/settings/picture")

@login_required
def getuserinfo(request, userid):
    JOB_CHOICE = {0:"学生", 1:"工程师", 2:"个体户", 3:"公务员", 4:"其他"}
    LIKE_STYLE_CHOICE = {0:"动作", 1:"悬疑", 2:"爱情", 3:"科幻", 4:"恐怖", 5:"犯罪", 6:"其他"}

    user = User.objects.get(pk=userid)
    # 如果用户没有填写资料
    if user.webuser.job_title == None:
        messages.add_message(request, messages.ERROR, "您要完善个人信息，才能进入个人信息页面")
        # 有一种可能性其他人访问该用户的userinfo,所以必须是当前用户.
        form = ProfileForm(instance=request.user,
                           initial={
                               "job_title":request.user.webuser.job_title,
                               "url":request.user.webuser.url,
                               "location":request.user.webuser.location,
                               "sex":request.user.webuser.sex,
                               "likestyle":request.user.webuser.likesstyle
                           })
        return render(request, "webuser/person_home_page_info.html", {"form":form})

    job = JOB_CHOICE[int(user.webuser.job_title)]
    likestyle_list = []
    for likestyle in user.webuser.likesstyle[1:-1].split(","):
        likestyle_list.append(LIKE_STYLE_CHOICE[int(likestyle.strip()[2])])
    friends = user.webuser.friends.all()
    return render(request, "webuser/userinfo.html", {"user":user, "job":job, "friends":friends, "likestyle_list":likestyle_list})

@login_required
def addfriends(request):
    """
    添加好友
    """
    if request.method == "POST":
        data = json.loads(request.POST.get("data"))
        friendid = data["friendid"]
        actiontype = data["actiontype"]
        if actiontype == "friend":
            # 获取当前用户的webuser
            webuser = request.user.webuser
            if webuser.id == int(friendid):
                return HttpResponse("error")
            # 根据friendid获取到用户webuser
            friend = Webuser.objects.get(pk=friendid)
            # 将friend添加到该用户的好友里
            webuser.friends.add(friend)
        return HttpResponse("success")
    else:
        return HttpResponse("error")

@login_required
def concern_issues(request):
    """
    当前用户关注问题的视图函数.
    """
    source = "concern_issues"
    user = request.user
    activites = Activity.objects.filter(activity_type=Activity.FAVORITE, user=user)
    questions = []
    for activity in activites:
        question = get_object_or_404(Question, pk=activity.question)
        questions.append(question)
    # 对关注的问题进行分页
    paginator = Paginator(questions, 10)
    page = request.GET.get("page")
    if page is not None:
        page = int(page)
    else:
        page = 1
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:

templates/webuser/change_email.html
{% extends "webuserbase.html" %}

{% block title %} 修改邮箱 {% endblock title %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <h1 class="page-header">修改邮箱</h1>
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            <form role="form" class="ChangePasswordForm" action="{% url 'webuser:webuser_email' %}" method="post" role="form">
                {% csrf_token %}
                {{ form.id }}
                <fieldset>
                    {% for field in form.visible_fields %}
                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                            <label for="{{ field.label }}">{{ field.label }}</label>
                            {{ field }}
                            {% if field.help_text %}
                                <span class="help-block">{{ field.help_text|safe }}</span>
                            {% endif %}
                            {% for error in field.errors %}
                                <label class="control-label">{{ error }}</label>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </fieldset>
                <div class="form-group">
                    <div class="form-group-left">
                        <button type="submit" class="btn btn-large btn-primary">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock page_content %}

templates/webuser/change_password.html
{% extends "webuserbase.html" %}

{% block title %} 修改密码 {% endblock title %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <h1 class="page-header">修改密码</h1>
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            <form role="form" class="ChangePasswordForm" action="{% url 'webuser:webuser_password' %}" method="post" role="form">
                {% csrf_token %}
                {{form.id}}
                <fieldset>
                    {% for field in form.visible_fields %}
                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                            <label for="{{ field.label }}">{{ field.label }}</label>
                            {{ field }}
                            {% if field.help_text %}
                                <span class="help-block">{{ field.help_text|safe }}</span>
                            {% endif %}
                            {% for error in field.errors %}
                                <label class="control-label">{{ error }}</label>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </fieldset>
                <div class="form-group">
                    <div class="form-group-left">
                        <button type="submit" class="btn btn-large btn-primary">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock page_content %}

templates/webuser/concern_issues.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load static %}

{% block title %} 关注的问题 {% endblock title %}
{% block head %}
    <link href="{% static 'questions/css/questions.css' %}" rel="stylesheet">
    <script src="{% static 'questions/js/questions.js' %}"></script>
{% endblock %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <div class="header">
            <ol class="breadcrumb">
                <li><a href="{% url 'webuser:webuser_settings' %}">{% trans "我的主页" %}</a></li>
                <li class="active">{% trans "我关注的问题" %}</li>
            </ol>
        </div>

        <div class="questions">
            {% for question in questions %}
                {% include 'questions/partial_question.html' with question=question source=source %}
            {% empty %}
                <h4 class="no-data">{% trans "你目前没有关注的问题." %}</h4>
            {% endfor %}
            {% include 'questions/paginator.html' with paginator=questions %}
        </div>
    </div>
</div>
{% endblock page_content %}

templates/webuser/partial_my_answer.html
{% load i18n %}
{% load humanize %}

<div class="row answer" answer-id="{{ answer.id }}">
{% csrf_token %}
    <div class="panel-heading">
        <h3 class="panel-title">
        {% if answer.question.has_accepted_answer %}
            <span class="glyphicon glyphicon-ok"></span>
        {% endif %}
        <a href="{% url 'questions:question' answer.question.pk %}">{{ answer.get_question_title|safe }}</a>
        </h3>
    </div>
    <div class="col-md-1 options">
        <span class="glyphicon glyphicon-chevron-up vote up-vote{% if user in answer.get_up_voters %} voted{% endif %}" title="{% trans '赞成' %}"></span>
        <span class="votes">{{ answer.votes }}</span>
        <span class="glyphicon glyphicon-chevron-down vote down-vote{% if user in answer.get_down_voters %} voted{% endif %}" title="{% trans '反对' %}"></span>
    </div>
    <div class="col-md-11">
        <div class="answer-user">
            <a><img src="{{ answer.user.webuser.get_picture }}" class="media-object img-circle" style='max-width:40px;'></a>
            <a href="{% url 'webuser:getuserinfo' answer.user.id %}" class="username">{{ answer.user.username }}</a>
            <small class="answered">{% trans "在" %} {{ answer.create_date|naturaltime }}{% trans "回答" %}</small>
        </div>
        <div class="answer-description">
            {{ answer.get_answercontent_as_markdown|safe }}
        </div>
    </div>
</div>

templates/webuser/person_home_page.html
{% extends "webuserbase.html" %}

{% block title %} 个人主页 {% endblock title %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar">
                    <div class="list-group">
                        <a class="list-group-item selected" href="{% url 'webuser:getuserinfo' user.id %}">个人信息</a>
                        <a class="list-group-item selected" href="{% url 'webuser:webuser_picture' %}">上传头像</a>
                        <a class="list-group-item selected" href="{% url 'webuser:my_questions' %}">我的提问</a>
                        <a class="list-group-item selected" href="{% url 'webuser:my_answer' %}">我的回答</a>
                        <a class="list-group-item selected" href="{% url 'webuser:concern_issues' %}">我关注的问题</a>
                        <a class="list-group-item selected" href="">关于我们</a>
                    </div>
                </div>
            </div>

            <!--显示左边菜单点击后的内容-->
            <div class="col-md-9">
                <div class="container">
                {%block person_home_content%}
                    <!--显示个人主页中间主要内容-->
                    <!--end-->
                {%endblock%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}

templates/webuser/picture.html
{% extends "webuser/person_home_page.html" %}
{% load staticfiles %}
{% load i18n %}
{% load static %}

{% block title %} 上传头像 {% endblock title %}
{% block head %}
  <link href="{% static 'webuser/css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <script src="{% static 'webuser/js/jquery.Jcrop.min.js' %}"></script>
  <script src="{% static 'webuser/js/picture.js' %}"></script>
{% endblock %}

{% block person_home_content %}
<div class="col-md-6 container">
    <h3 class="page-header">上传头像</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <h1 style="margin-top:0"><small>更改头像</small></h1>
    <img src="{{ user.webuser.get_picture }}" style="width:150px;border-radius:5px;margin-bottom:lem;">
    <form enctype="multipart/form-data" method="post" action="{% url 'webuser:upload_picture' %}" id="picture-upload-form">
        {% csrf_token%}
        <input type="file" name="picture" style="display:none"><br>
        <button type="button" class="btn btn-primary" id="btn-upload-picture">上传照片</button>
    </form>
    {% if uploaded_picture %}
        <form method="post" action="{% url 'webuser:save_uploaded_picture' %}">
            {%csrf_token%}
            <div class="modal fade" id="modal-upload-picture">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">'上传图片'</h4>
                        </div>
                        <div class="modal-body">
                            <div class="selected-picture">
                                <p>首先裁剪图片，然后点击<strong>保存图片</strong>按钮</p>
                                <img src="{{ MEDIA_URL }}webuser_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                                <input type="hidden" id="x" name="x" />
                                <input type="hidden" id="y" name="y" />
                                <input type="hidden" id="w" name="w" />
                                <input type="hidden" id="h" name="h" />
                            </div>
                            <script type="text/javascript">
                            $(function () {
                                $("#modal-upload-picture").modal();
                                window.history.pushState("", "", "/settings/picture/");
                            });
                            </script>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                            <button type="submit" class="btn btn-primary">保存图片</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    {% endif %}
</div>
{% endblock person_home_content %}

templates/webuser/userinfo.html
{% extends "webuserbase.html" %}
{% load staticfiles %}
{% load i18n %}
{% load static %}

{% block title %} 个人主页 {% endblock title %}

{% block head %}

<link href="{% static 'webuser/css/user.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
    <script type="text/javascript">
        $(document).ready(function(){
            $(".action").click(function(){
                var friendid = $(this).attr('friendid');
                var actiontype = $(this).attr('actiontype')
                var friend_dic={
                'friendid':friendid,
                'actiontype':actiontype
                }
                console.log("actiontype:"+actiontype+friendid)
            $.post("{% url 'webuser:addfriends' %}",{'data':JSON.stringify(friend_dic),'csrfmiddlewaretoken':GetCsrfToken()},function(callback){
                console.log(callback)
            });//post
            $(this).addClass('disabled')
            alert("他已经是你好友啦.......")
            });//end click
        });//end document ready
function GetCsrfToken(){
    return $("input[name='csrfmiddlewaretoken']").val();
    }
    </script>
{% endblock head %}

{% block page_content %}
<div id="mainbody">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'webuser:webuser_settings' %}">{% trans "我的主页" %}</a></li>
            <li class="active">{% trans "个人信息" %}</li>
        </ol>
        <small><h3 class="page-header" style="text-align:center;">个人信息</h3></small>
        <div class="row">
            {% csrf_token %}
            <div class="col-md-4 col-sm-4 portrait">
                <img src="{{ user.webuser.get_picture }}" style="width:140px;height:140px;" class="img-responsive img-circle" alt="国民">
            </div>
            <div class="col-md-4 col-sm-4 userinfo">
                <h3>{{ user.username }}</h3>
                <h5>邮箱: {{ user.email }}</h5>
                <h5>职业: {{ job }}</h5>
                <h5>喜欢电影的类型:</h5>
                {% for likestyle in likestyle_list %}
                      <a>{{ likestyle }}</a>
                {% endfor %}             
            </div>
            <div class="col-md-2 col-sm-2">
                <p><button type="button" class="btn btn-primary action disabled" friendid="{{user.webuser.id}}" actiontype="view"><span class="glyphicon glyphicon-leaf">关注此人</span> </button></p>
                <p><button type="button" class="btn btn-danger action" friendid="{{ user.webuser.id }}" actiontype="friend"><span class="glyphicon glyphicon-plus">加为好友</span> </button></p>
            </div>
        </div>
        <small><h3 class="page-header" style="text-align:center;">{{ user.username }}的好友</h3></small>
        <div class="row">
            <div class="col-md-4 col-sm-4 userinfo">
                <ul class="nav navbar-nav">
                {% for friend in friends %}
                    <li>
                        <p><h5 style="text-align:center" href="{% url 'webuser:getuserinfo' friend.user.id %}">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'webuser:getuserinfo' friend.user.id %}">
                                {{ friend.user }}
                            </a>                            
                        </h5></p>
                        <img src="{{ friend.get_picture }}" style="width:50px;height:50px;" class="img-responsive img-circle">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </li>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}