blog/urls.py
#coding:utf-8

from django.conf.urls import url
import views

# app_name是为了reverse函数准备的
app_name = "blog"
# ^$代表了空字符串
urlpatterns = [
    url(r'^blog/$', views.IndexView.as_view(), name="index"),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^blog/archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name="archives"),
    url(r'^blog/category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^blog/tag/(?P<pk>[0-9]+)/$', views.TagViews.as_view(), name="tag"),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('webuser.urls')),
    url(r'', include('movie.urls')),
    url(r'', include('questions.urls')),
    url(r'', include('webchat.urls')),
    url(r'', include('weixin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
#coding:utf-8

from django.conf.urls import url
import views

# app_name是为了reverse函数准备的
app_name = "movie"
# ^$代表了空字符串
urlpatterns = [
    url(r'^getmovielist/$', views.get_movie_list, name="getmovielist"),
    url(r'^getlatestmovielist/$', views.get_latest_movielist, name="getlatestmovielist"),
    url(r'^getfilmfestlist/$', views.get_filmfest_list, name="getfilmfestlist"),
    url(r'^searchmovie/$', views.search_movie, name="searchmovie"),
    url(r'^movie/(?P<movie_id>[0-9]+)/$', views.movie, name="movie"),
    url(r'^ranking_list/playmostmovies/$', views.get_playmostmovies, name="playmostmovies"),
    url(r'^ranking_list/box_officemovies/$', views.get_box_officemovies, name="box_officemovies"),
    url(r'^ranking_list/good_evaluationmovies/$', views.get_good_evaluationmovies, name="good_evaluationmovies"),
]

questions/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "questions"
# ^$代表了空字符串
urlpatterns = [
    url(r'^questions/$', views.questions, name="questions"),
    url(r'^questions/unanswered_questions$', views.unanswered_questions, name="unanswered_questions"),
    url(r'^questions/answered_questions$', views.answered_questions, name="answered_questions"),
    url(r'^questions/(?P<questionid>[0-9]+)/$', views.question, name="question"),
    url(r'^questions/ask/$', views.ask, name="ask"),
    url(r'^questions/answer/(?P<questionid>[0-9]+)/$', views.answer, name="answer"),
    url(r'^questions/answer/accept/$', views.accept, name="accept"),
    url(r'^questions/answer/vote/$', views.vote, name="vote"),
    url(r'^questions/favorite/$', views.favorite, name="favorite"),
]

webchat/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "webchat"
# ^$代表了空字符串
urlpatterns = [
    url(r'^webchat/$', views.webchat, name="webchat"),
    url(r'^webchat/contacts/$', views.contacts, name="load_contact_list"),
    url(r'^webchat/newmessage/$', views.newmessage, name="send_msg"),
    url(r'^webchat/newmessage/$', views.newmessage, name="get_new_msgs"),
]

webuser/urls.py
#coding:utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

import views

# app_name是为了reverse函数准备的
app_name = "webuser"
# ^$代表了空字符串
urlpatterns = [
    url(r'^$', views.index, name="webuser_index"),
    url(r'^weblogin/$', views.web_login, name="webuser_login"),
    url(r'^register/$', views.register, name="webuser_register"),
    url(r'^settings/$', views.settings, name="webuser_settings"),
    url(r'^settings/picture/$', views.picture, name="webuser_picture"),
    url(r'^settings/upload_picture/$', views.upload_picture, name="upload_picture"),
    url(r'^settings/save_uploaded_picture/$', views.save_uploaded_picture, name="save_uploaded_picture"),
    url(r'^settings/addfriends/$', views.addfriends, name="addfriends"),
    url(r'^webuser/concern_issues/$', views.concern_issues, name="concern_issues"),    # 关注的问题
    url(r'^webuser/my_questions/$', views.my_questions, name="my_questions"),    # 用户提的问题
    url(r'^webuser/my_answer/$', views.my_answer, name="my_answer"),    # 用户的回答
    url(r'^webuser/changepassword/$', views.change_password, name="webuser_password"),
    url(r'^webuser/changeemail/$', views.change_email, name="webuser_email"),
    url(r'^webuser/getuserinfo/(?P<userid>[0-9]+)/$', views.getuserinfo, name="getuserinfo"),
    url(r'^weblogout/$', auth_views.logout, {"next_page":"/"}, name="webuser_logout"),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Code &amp; Data</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/flickr.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Code</b> &amp; Data</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="#">叶小乖的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as post_list %}
                    <ul>
                        {% for post in post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章.
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">文章存档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">
                                {{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无文章.
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-category">
                    <h3 class="widget-title">文章分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.post_set.count }})</span></a>
                        </li>
                        {% empty %}
                        暂无文章.
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url "blog:tag" tag.pk %}">{{ tag.name }}</a>
                        </li>  
                        {% empty %}
                        暂无标签.
                        {% endfor %}                     
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="#" title="网页模板" target="_blank">叶小乖blog</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>


</body>
</html>

templates/blogbase.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Code &amp; Data</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/flickr.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Code</b> &amp; Data</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'webuser:webuser_index' %}" data-hover="电影">电影</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="#">叶小乖的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as post_list %}
                    <ul>
                        {% for post in post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章.
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">文章存档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">
                                {{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无文章.
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-category">
                    <h3 class="widget-title">文章分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.post_set.count }})</span></a>
                        </li>
                        {% empty %}
                        暂无文章.
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url "blog:tag" tag.pk %}">{{ tag.name }}</a>
                        </li>  
                        {% empty %}
                        暂无标签.
                        {% endfor %}                     
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="#" title="网页模板" target="_blank">叶小乖blog</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>


</body>
</html>

templates/webuserbase.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="shortcut icon" href="{% static 'webuser/vimeo.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'webuser/vimeo.ico' %}" type="image/x-icon">
    <title>{% block title %}基础页面{% endblock title %}</title>

    <link href="{% static 'webuser/css/reset.css' %}" rel="stylesheet">
    <link href="{% static 'webuser/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'webuser/css/common.css' %}" rel="stylesheet">
    <link href="{% static 'webuser/css/person_home_info.css' %}" rel="stylesheet">
    <link href="{% static 'webuser/css/styles.css' %}" rel="stylesheet">

    <script src="{% static 'webuser/lib/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'webuser/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'webuser/lib/holder.js' %}"></script>
    <script src="{% static 'webuser/js/app.js' %}"></script>
    <script src="{% static 'webuser/js/common.js' %}"></script>

    {% block head %}
    {% endblock head %}
</head>

<body>
{% csrf_token %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'blog:index' %}" class="navbar-brand"><strong>code&data</strong>.com</a>
            </div>
            <div class="collapse navbar-collapse" id="responsive-navbar">
                <ul class="nav navbar-nav">
                    <li {% if action == 'webuser' %} class="active" {% endif %}><a href="{% url 'webuser:webuser_index' %}">首页</a></li>
                    <li {% if action == 'getmovielist' %} class="active" {% endif %}><a href="{% url 'movie:getmovielist' %}">电影池</a></li>
                    <li {% if action == 'rankinglist' %} class="active" {% endif %}><a href="{% url 'movie:playmostmovies' %}">排行榜</a></li>
                    <li {% if action == 'questions' %} class="active" {% endif %}><a href="{% url 'questions:questions' %}">找电影</a></li>
                    <li {% if action == 'webchat' %} class="active" {% endif %}><a href="{% url 'webchat:webchat' %}">聊电影</a></li>
                </ul>
                <form action="{% url 'movie:searchmovie' %}" class="navbar-form navbar-left">
                    <input type="text" placeholder="电影搜索" class="form-control movie-search" name="q">
                    <button type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
                <a href="http://119.29.143.106/webuser/" title="收藏网站" class="btn btn-primary btn-sm navbar-btn navbar-right hidden-xs" onclick="window.external.addFavorite(this.href,this.title);return false;" rel="sidebar">收藏网站</a>
                <div class="profile navbar-right">
                    <ul class="nav navbar-nav">
                        {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ request.user.webuser.get_picture }}" style="width:30px;border-radius:1px;margin-bottom:lem;">
                                {{ request.user }}<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'webuser:webuser_settings' %}" class="glyphicon glyphicon-user">我的主页</a> </li>
                                <li><a href="{% url 'webuser:webuser_password' %}" class="glyphicon glyphicon-edit">修改密码</a> </li>
                                <li><a href="{% url 'webuser:webuser_email' %}" class="glyphicon glyphicon-th">修改邮箱</a> </li>
                                <li><a href="{% url 'webuser:webuser_logout' %}" class="glyphicon glyphicon-off">退出登录</a> </li>
                            </ul>
                        </li>
                        {% else %}
                        <li><a href="{% url 'webuser:webuser_login' %}">登录</a></li>
                        <li><a href="{% url 'webuser:webuser_register' %}">注册</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>

{% block content %}
    <div class="container">
    </div>
    {% block slideshow %}{% endblock slideshow %}
    {% block page_content %}{% endblock page_content %}

<!--footer开始-->
    <div id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-8"> Copyright &copy; code&data.com</div>
                <div class="col-md-2">
                    <a href="#">回到顶部</a>
                </div>
            </div>
        </div>
    </div>
<!--footer结束 -->
{% endblock content %}

{% block allfilms %}{% endblock allfilms %}
{% block index %}{% endblock index %}
</body>
</html>